/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package travelsetia;

import java.awt.Color;

/**
 *
 * @author dimas
 */
public class MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PAdmin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        PmainMember = new javax.swing.JPanel();
        PgarisMember = new javax.swing.JPanel();
        iconMember = new javax.swing.JLabel();
        JLMember = new javax.swing.JLabel();
        PmainPesawat = new javax.swing.JPanel();
        PgarisPesawat = new javax.swing.JPanel();
        iconPesawat = new javax.swing.JLabel();
        JLPesawat = new javax.swing.JLabel();
        PmainDashboard = new javax.swing.JPanel();
        iconDash = new javax.swing.JLabel();
        JLDashboard = new javax.swing.JLabel();
        PgarisDashboard = new javax.swing.JPanel();
        jButtonBackAdmin = new javax.swing.JButton();
        panel_kanan = new javax.swing.JPanel();
        panel_atas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panel_tengah = new javax.swing.JPanel();
        panelTengahDashboard = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        PAdmin.setBackground(new java.awt.Color(255, 255, 255));
        PAdmin.setPreferredSize(new java.awt.Dimension(300, 774));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_icon/Palm Treereng.png"))); // NOI18N

        jLabel15.setBackground(new java.awt.Color(53, 114, 239));
        jLabel15.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(53, 114, 239));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("TRAVEL SETIA");

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("MASTER DATA");

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Libraries");

        PmainMember.setBackground(new java.awt.Color(255, 255, 255));

        PgarisMember.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PgarisMemberLayout = new javax.swing.GroupLayout(PgarisMember);
        PgarisMember.setLayout(PgarisMemberLayout);
        PgarisMemberLayout.setHorizontalGroup(
            PgarisMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        PgarisMemberLayout.setVerticalGroup(
            PgarisMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        iconMember.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_icon/People.png"))); // NOI18N

        JLMember.setText("Akun Custumer");
        JLMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLMemberMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JLMemberMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JLMemberMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PmainMemberLayout = new javax.swing.GroupLayout(PmainMember);
        PmainMember.setLayout(PmainMemberLayout);
        PmainMemberLayout.setHorizontalGroup(
            PmainMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PmainMemberLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PgarisMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconMember, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLMember, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PmainMemberLayout.setVerticalGroup(
            PmainMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PmainMemberLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PmainMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PgarisMember, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconMember, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(JLMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PmainPesawat.setBackground(new java.awt.Color(255, 255, 255));

        PgarisPesawat.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PgarisPesawatLayout = new javax.swing.GroupLayout(PgarisPesawat);
        PgarisPesawat.setLayout(PgarisPesawatLayout);
        PgarisPesawatLayout.setHorizontalGroup(
            PgarisPesawatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        PgarisPesawatLayout.setVerticalGroup(
            PgarisPesawatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        iconPesawat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconPesawat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_icon/Plane.png"))); // NOI18N

        JLPesawat.setText("Pesawat");
        JLPesawat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLPesawatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JLPesawatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JLPesawatMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PmainPesawatLayout = new javax.swing.GroupLayout(PmainPesawat);
        PmainPesawat.setLayout(PmainPesawatLayout);
        PmainPesawatLayout.setHorizontalGroup(
            PmainPesawatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PmainPesawatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PgarisPesawat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconPesawat, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLPesawat, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PmainPesawatLayout.setVerticalGroup(
            PmainPesawatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PmainPesawatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PmainPesawatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PgarisPesawat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconPesawat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(JLPesawat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PmainDashboard.setBackground(new java.awt.Color(255, 255, 255));
        PmainDashboard.setPreferredSize(new java.awt.Dimension(253, 48));

        iconDash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconDash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_icon/Laptop Metrics.png"))); // NOI18N

        JLDashboard.setText("Dashboard");
        JLDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLDashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JLDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JLDashboardMouseExited(evt);
            }
        });

        PgarisDashboard.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PgarisDashboardLayout = new javax.swing.GroupLayout(PgarisDashboard);
        PgarisDashboard.setLayout(PgarisDashboardLayout);
        PgarisDashboardLayout.setHorizontalGroup(
            PgarisDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        PgarisDashboardLayout.setVerticalGroup(
            PgarisDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PmainDashboardLayout = new javax.swing.GroupLayout(PmainDashboard);
        PmainDashboard.setLayout(PmainDashboardLayout);
        PmainDashboardLayout.setHorizontalGroup(
            PmainDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PmainDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PgarisDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconDash, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addContainerGap())
        );
        PmainDashboardLayout.setVerticalGroup(
            PmainDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PmainDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PmainDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PgarisDashboard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconDash, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(JLDashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButtonBackAdmin.setText("Logout");
        jButtonBackAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBackAdminMouseClicked(evt);
            }
        });
        jButtonBackAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PAdminLayout = new javax.swing.GroupLayout(PAdmin);
        PAdmin.setLayout(PAdminLayout);
        PAdminLayout.setHorizontalGroup(
            PAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAdminLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(PAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBackAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PmainMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PmainPesawat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PAdminLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel12)))
                    .addComponent(PmainDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        PAdminLayout.setVerticalGroup(
            PAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAdminLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(PAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PAdminLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PmainDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PmainPesawat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PmainMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 428, Short.MAX_VALUE)
                .addComponent(jButtonBackAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        getContentPane().add(PAdmin, java.awt.BorderLayout.LINE_START);

        panel_kanan.setBackground(new java.awt.Color(255, 255, 255));
        panel_kanan.setLayout(new java.awt.BorderLayout());

        panel_atas.setBackground(new java.awt.Color(102, 153, 255));
        panel_atas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hello! Admin");
        panel_atas.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, 30));

        minimize.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        minimize.setForeground(new java.awt.Color(255, 255, 255));
        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setText("-");
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        panel_atas.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 40, 40));

        exit.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("x");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        panel_atas.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 40, 40));
        panel_atas.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 88, -1, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_icon/Admin Settings Male.png"))); // NOI18N
        panel_atas.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 60, 60));

        panel_kanan.add(panel_atas, java.awt.BorderLayout.PAGE_START);

        panelTengahDashboard.setBackground(new java.awt.Color(255, 255, 255));
        panelTengahDashboard.setPreferredSize(new java.awt.Dimension(928, 599));
        panelTengahDashboard.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout panel_tengahLayout = new javax.swing.GroupLayout(panel_tengah);
        panel_tengah.setLayout(panel_tengahLayout);
        panel_tengahLayout.setHorizontalGroup(
            panel_tengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tengahLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTengahDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 936, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_tengahLayout.setVerticalGroup(
            panel_tengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tengahLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTengahDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel_kanan.add(panel_tengah, java.awt.BorderLayout.CENTER);

        getContentPane().add(panel_kanan, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(MenuCustomer.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void JLDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLDashboardMouseExited
        // merubah kembali ke awal warna
        PmainDashboard.setBackground(new Color(255,255,255));
        PgarisDashboard.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_JLDashboardMouseExited

    private void JLDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLDashboardMouseEntered
        // merubah warna dashboard
        PmainDashboard.setBackground(new Color(250,250,250));
        PgarisDashboard.setBackground(new Color(102,153,255));
    }//GEN-LAST:event_JLDashboardMouseEntered

    private void JLDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLDashboardMouseClicked
        // menampilkan panel dashboard
        PmainDashboard.setBackground(new Color(240,240,240));
        PgarisDashboard.setBackground(new Color(102,153,255));

        panelTengahDashboard.removeAll();
        panelTengahDashboard.add(new MenuDashboard2());
        panelTengahDashboard.repaint();
        panelTengahDashboard.revalidate();

    }//GEN-LAST:event_JLDashboardMouseClicked

    private void JLPesawatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLPesawatMouseExited
        // TODO add your handling code here:
        PmainPesawat.setBackground(new Color(255,255,255));
        PgarisPesawat.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_JLPesawatMouseExited

    private void JLPesawatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLPesawatMouseEntered
        // TODO add your handling code here:
        PmainPesawat.setBackground(new Color(250,250,250));
        PgarisPesawat.setBackground(new Color(102,153,255));
    }//GEN-LAST:event_JLPesawatMouseEntered

    private void JLPesawatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLPesawatMouseClicked
        // menampilkan panel pesawat
        PmainPesawat.setBackground(new Color(240,240,240));
        PgarisPesawat.setBackground(new Color(102,153,255));

        panelTengahDashboard.removeAll();
        panelTengahDashboard.add(new MenuPesawat1());
        panelTengahDashboard.repaint();
        panelTengahDashboard.revalidate();
    }//GEN-LAST:event_JLPesawatMouseClicked

    private void JLMemberMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLMemberMouseExited
        // TODO add your handling code here:
        PmainMember.setBackground(new Color(255,255,255));
        PgarisMember.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_JLMemberMouseExited

    private void JLMemberMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLMemberMouseEntered
        // TODO add your handling code here:
        PmainMember.setBackground(new Color(250,250,250));
        PgarisMember.setBackground(new Color(102,153,255));
    }//GEN-LAST:event_JLMemberMouseEntered

    private void JLMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLMemberMouseClicked
        // TODO add your handling code here:
        PmainMember.setBackground(new Color(240,240,240));
        PgarisMember.setBackground(new Color(102,153,255));

        panelTengahDashboard.removeAll();
        panelTengahDashboard.add(new MenuMember());
        panelTengahDashboard.repaint();
        panelTengahDashboard.revalidate();
    }//GEN-LAST:event_JLMemberMouseClicked

    private void jButtonBackAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBackAdminActionPerformed

    private void jButtonBackAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBackAdminMouseClicked
        Login1 Login1Frame = new Login1();
        Login1Frame.setVisible(true);
        Login1Frame.pack();
        Login1Frame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonBackAdminMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLDashboard;
    private javax.swing.JLabel JLMember;
    private javax.swing.JLabel JLPesawat;
    private javax.swing.JPanel PAdmin;
    private javax.swing.JPanel PgarisDashboard;
    private javax.swing.JPanel PgarisMember;
    private javax.swing.JPanel PgarisPesawat;
    private javax.swing.JPanel PmainDashboard;
    private javax.swing.JPanel PmainMember;
    private javax.swing.JPanel PmainPesawat;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel iconDash;
    private javax.swing.JLabel iconMember;
    private javax.swing.JLabel iconPesawat;
    private javax.swing.JButton jButtonBackAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel minimize;
    private javax.swing.JPanel panelTengahDashboard;
    private javax.swing.JPanel panel_atas;
    private javax.swing.JPanel panel_kanan;
    private javax.swing.JPanel panel_tengah;
    // End of variables declaration//GEN-END:variables
}
