/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package travelsetia;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dimas
 */
public class MenuBooking1 extends javax.swing.JPanel {

    private DefaultTableModel model = new DefaultTableModel();
    private Connection conn;

    public MenuBooking1() {
        initComponents();
        loadDataToTable();
    }

    private void loadDataToTable() {
        conn = Koneksi.bukaKoneksi();
        System.out.println(conn);
        String sql = "SELECT dt.idTransaksi, dt.idBooking, dt.tanggalTransaksi, dt.jumlahPembayaran, dt.namaPenumpang FROM detail_transaksi dt JOIN booking b ON dt.idBooking = b.idBooking";

        try (PreparedStatement pst = conn.prepareStatement(sql); ResultSet rs = pst.executeQuery()) {

            // Inisialisasi DefaultTableModel dengan kolom yang ditentukan
            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(new Object[]{
                "ID Transaksi",
                "ID Booking",
                "Tanggal Booking",
                "Jumlah Pembayaran",
                "Nama Penumpang"
            });

            // Memproses ResultSet dan menambahkan data ke model
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("idTransaksi"),
                    rs.getString("idBooking"),
                    rs.getString("tanggalTransaksi"),
                    rs.getString("jumlahPembayaran"),
                    rs.getString("namaPenumpang")
                });
            }

            // Set model ke JTable
            tabelPenumpang.setModel(model);
            tabelPenumpang.setDefaultEditor(Object.class, null); // Nonaktifkan pengeditan sel
            tabelPenumpang.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); // Hanya pilih satu baris

        } catch (SQLException ex) {
            System.out.println("Error: " + ex.getMessage());
        }
    }

    private int hitungPesawat() {
        int totalPesawat = 0;
        String sql = "SELECT COUNT(*) AS total FROM pesawat";

        try (PreparedStatement pstmt = conn.prepareStatement(sql); ResultSet rs = pstmt.executeQuery()) {
            if (rs.next()) {
                totalPesawat = rs.getInt("total");
            }
        } catch (SQLException e) {
            System.out.println("Error retrieving total aircraft: " + e.getMessage());
        }

        return totalPesawat;
    }

    private int hitungBandara() {
        int totalBandara = 0;
        String sql = "SELECT COUNT(*) AS totalBandara FROM bandara";

        try (PreparedStatement pstmt = conn.prepareStatement(sql); ResultSet rs = pstmt.executeQuery()) {
            if (rs.next()) {
                totalBandara = rs.getInt("totalBandara");
            }
        } catch (SQLException e) {
            System.out.println("Error retrieving total aircraft: " + e.getMessage());
        }

        return totalBandara;
    }

    private int hitungCustomer() {
        int totalCustomer = 0;
        String sql = "SELECT COUNT(*) AS totalCustomer FROM detail_transaksi";

        try (PreparedStatement pstmt = conn.prepareStatement(sql); ResultSet rs = pstmt.executeQuery()) {
            if (rs.next()) {
                totalCustomer = rs.getInt("totalCustomer");
            }
        } catch (SQLException e) {
            System.out.println("Error retrieving total aircraft: " + e.getMessage());
        }

        return totalCustomer;
    }

    private void insertDetailBooking() {
        String sql = "INSERT INTO detail_booking (idDetail, idBooking, idPenumpang, tanggalBooking) VALUES (?, ?, ?, ?)";
        try {
            Connection conn = Koneksi.bukaKoneksi();
            PreparedStatement pstmt = conn.prepareStatement(sql);
            java.sql.Date currentDate = new java.sql.Date(System.currentTimeMillis());

            pstmt.executeBatch();
        } catch (SQLException e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPenumpang = new javax.swing.JTable();
        iconMember = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(53, 114, 239));
        jPanel1.setPreferredSize(new java.awt.Dimension(928, 599));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Data penumpang per booking");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 250, 30));

        tabelPenumpang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Data penumpang", "Data penerbangan"
            }
        ));
        jScrollPane1.setViewportView(tabelPenumpang);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 760, 490));

        iconMember.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_icon/People.png"))); // NOI18N
        jPanel1.add(iconMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 50, 30));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Master Data > Data Penumpang");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 260, 30));

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconMember;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelPenumpang;
    // End of variables declaration//GEN-END:variables
}
