package travelsetia;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableRowSorter;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author dimas
 */
public class MenuMember extends javax.swing.JPanel {

    private Connection conn;

    public MenuMember() {
        initComponents();
        loadDataToTable();

    }

    private void loadDataToTable() {

        conn = Koneksi.bukaKoneksi();
        System.out.println(conn);
        String sql = "SELECT a.idPenumpang AS idAkun, a.email AS email_akun, a.userPassword AS userPassword_akun, p.destinasi AS destinasi_pesawat FROM akun a LEFT JOIN pesawat p ON a.idPenumpang = p.idPesawat; ";
        try {
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(new Object[]{"ID Akun", "Email Pengguna", "Password Pengguna", "Destinasi", "Tiket Terbeli"});

            while (rs.next()) {
               
                int idPenumpang = rs.getInt("idAkun");
                int tiketTerjual = hitungTiketTerjual(idPenumpang);

               
                model.addRow(new Object[]{
                    rs.getInt("idAkun"),
                    rs.getString("email_akun"),
                    rs.getString("userPassword_akun"),
                    rs.getString("destinasi_pesawat"),
                    tiketTerjual

                });
            }

            tabelPenumpang.setModel(model);
            tabelPenumpang.setDefaultEditor(Object.class, null);

        } catch (Exception ex) {
            System.out.println("Error : " + ex.getMessage());
        }
    }

    private void deleteSelectedRow() {
        int row = tabelPenumpang.getSelectedRow();
        if (row != -1) {
            DefaultTableModel model = (DefaultTableModel) tabelPenumpang.getModel();
            int idPesawat = (int) model.getValueAt(row, 0);

            // Hapus dari database
            String sql = "DELETE FROM pesawat WHERE idPenumpang = ?";
            try {
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setInt(1, idPesawat);
                pst.executeUpdate();
                System.out.println("Row deleted successfully.");
            } catch (Exception ex) {
                System.out.println("Error : " + ex.getMessage());
            }

            // Hapus dari tabel
            model.removeRow(row);
        }
    }

    private int hitungTiketTerjual(int idPesawat) {
        int totalTiketTerjual = 0;
        String sql = "SELECT SUM(jumlahTiket) AS total FROM booking WHERE idPesawat = ?";
        try {
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, idPesawat);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                totalTiketTerjual = rs.getInt("total");
            }
        } catch (SQLException e) {
            System.out.println("Error retrieving total tiket terjual: " + e.getMessage());
        }
        return totalTiketTerjual;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPenumpang = new javax.swing.JTable();
        iconMember = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setBackground(new java.awt.Color(53, 114, 239));
        setPreferredSize(new java.awt.Dimension(928, 599));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Data Akun Penumpang");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 190, 30));

        tabelPenumpang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelPenumpang);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 760, 430));

        iconMember.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_icon/People.png"))); // NOI18N
        add(iconMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 40, 30));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Master Data > Akun Penumpang");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 260, 30));

        jButton6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(102, 153, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_icon/Minus.png"))); // NOI18N
        jButton6.setText("Hapus");
        jButton6.setBorder(null);
        jButton6.setPreferredSize(new java.awt.Dimension(78, 25));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 140, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        deleteSelectedRow();
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconMember;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelPenumpang;
    // End of variables declaration//GEN-END:variables
}
